### ISSUE TITLE
How I can get the dataset witch you used?

### ISSUE THREAD

**Issue by EasyLuck** [naivewong/timeunion#1]
Hi~
There is a tag file dataset. But how to get the time-series samples?
Looking forward your reply. Thank you very much.

**Comment by naivewong** [comment]
Hi, I generate the data samples myself. For instance, in leveldb/db/dbtest.cc (https://github.com/naivewong/timeunion/blob/8070492d2c6a2d68175e7d026c27b858c2aec8e6/leveldb/db/dbtest.cc#L113)

**Comment by EasyLuck** [comment]
OK ,thank you.
