### ISSUE TITLE
I can not understand the source code.

### ISSUE THREAD

**Issue by EasyLuck** [naivewong/timeunion#2]

**Comment by EasyLuck** [comment]
Dear author:
Can you give me some advices for me? I need do research , but I can not understand the source code

**Comment by naivewong** [comment]
Actually, the codebase mainly consists  of two parts. The first part is the management of timeseries (indexes and in-memory data samples), and they are in folders except for leveldb. The second part is the management of the persistent data samples (I derive time-partitioned lsm tree based on LevelDB), which is contained in folder leveldb. For each folder, the main contents are as follows:

- base: basic helper functions for the codebase
- block: interfaces for chunk reader/writer, and index reader/writer
- chunk: compression of a set of data points into a chunk
- cloud: the AWS S3 wrapper for file operations on S3
- db: the tsdb object (in charge of everything)
- head: management of in-memory data (indexes and in-memory data samples), this is important
- index: mainly are different kinds of posting lists
- label: tags
- leveldb: time-partitioned LSM tree
- querier: the querier for all data, which has a global view (this is deprecated), the current querier is in leveldb/db/db_querier.h

Besides, you can read the [blogs](https://ganeshvernekar.com/blog/prometheus-tsdb-the-head-block/) of Prometheus for some basic concepts.
